name: Build Checks

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker Build
        run: docker-compose up --build
        env:
          FRIENDO_TOKEN: ${{ secrets.DEV_TOKEN }}
